[package]

name = "24daysofrust"
version = "0.0.1"
authors = ["Zbigniew Siciarz <zbigniew@siciarz.net>"]

[[bin]]
name = "day2"

[[bin]]
name = "day3"

[[bin]]
name = "day4"

[[bin]]
name = "day5"

[[bin]]
name = "day6"

[[bin]]
name = "day7"

[[bin]]
name = "day9"

[[bin]]
name = "day10"

[[bin]]
name = "day11"

[[bin]]
name = "day12"

[[bin]]
name = "day13"

[[bin]]
name = "day14"

[[bin]]
name = "day15"

[[bin]]
name = "day17"

[[bin]]
name = "day18"

[[bin]]
name = "day20"

[[bin]]
name = "day21"

[dependencies]
anymap = "~0.11.1"
csv = "~0.14.3"
clippy = "~0.0.15"
docopt = "~0.6.72"
docopt_macros = "~0.6.72"
fuse = "~0.2.7"
image = "~0.3.14"
itertools = "~0.3.25"
json_macros = "~0.2.5"
libc = "~0.1.10"
nalgebra = "~0.2.23"
num = "~0.1.27"
postgres_array = "~0.5.1"
postgres_macros = "~0.1.3"
postgres_range = "~0.7.3"
primal = "~0.2.3"
rand = "~0.3.11"
redis = "~0.3.1"
rust-crypto = "~0.2.31"
rustc-serialize = "~0.3.16"
time = "~0.1.32"
tau = "~1.0.3"
url = "~0.2.37"
uuid = "~0.1.17"
zmq = "~0.7.0"

[dependencies.hyper]
version = "~0.6.14"
features = ["nightly"]

[dependencies.postgres]
version= "~0.10.0"
features = ["rustc-serialize", "time"]
